name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Web
        run: flutter build web
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/web/index.html
            build/web/main.dart.js
            build/web/flutter.js
            build/web/flutter_service_worker.js
            build/web/flutter_bootstrap.js
            build/web/favicon.png
            build/web/manifest.json
            build/web/version.json
            build/web/assets/**/*
            build/web/canvaskit/canvaskit.js
            build/web/canvaskit/canvaskit.wasm
            build/web/canvaskit/skwasm.js
            build/web/canvaskit/skwasm.wasm
            build/web/canvaskit/skwasm.worker.js
            build/web/icons/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
